export const CREATE_ACCOUNTING_REQUEST = 'CREATE_ACCOUNTING_REQUEST';
export const CREATE_ACCOUNTING_SUCCESS = 'CREATE_ACCOUNTING_SUCCESS';
export const CREATE_ACCOUNTING_FAIL = 'CREATE_ACCOUNTING_FAIL';


export const MY_ACCOUNTINGS_REQUEST = 'MY_ACCOUNTINGS_REQUEST';
export const MY_ACCOUNTINGS_SUCCESS = 'MY_ACCOUNTINGS_SUCCESS';
export const MY_ACCOUNTINGS_FAIL = 'MY_ACCOUNTINGS_FAIL';

export const NEW_ACCOUNTING_RESET = 'NEW_ACCOUNTING_RESET';

export const ALL_ACCOUNTINGS_REQUEST = 'ALL_ACCOUNTINGS_REQUEST';
export const ALL_ACCOUNTINGS_SUCCESS = 'ALL_ACCOUNTINGS_SUCCESS';
export const ALL_ACCOUNTINGS_FAIL = 'ALL_ACCOUNTINGS_FAIL';



export const UPDATE_ACCOUNTING_REQUEST = 'UPDATE_ACCOUNTING_REQUEST';
export const UPDATE_ACCOUNTING_SUCCESS = 'UPDATE_ACCOUNTING_SUCCESS';
export const UPDATE_ACCOUNTING_RESET = 'UPDATE_ACCOUNTING_RESET';
export const UPDATE_ACCOUNTING_FAIL = 'UPDATE_ACCOUNTING_FAIL';




export const DELETE_ACCOUNTING_REQUEST = 'DELETE_ACCOUNTING_REQUEST';
export const DELETE_ACCOUNTING_SUCCESS = 'DELETE_ACCOUNTING_SUCCESS';
export const DELETE_ACCOUNTING_RESET = 'DELETE_ACCOUNTING_RESET';
export const DELETE_ACCOUNTING_FAIL = 'DELETE_ACCOUNTING_FAIL';


export const ACCOUNTING_DETAILS_REQUEST = 'ACCOUNTING_DETAILS_REQUEST';
export const ACCOUNTING_DETAILS_SUCCESS = 'ACCOUNTING_DETAILS_SUCCESS';
export const ACCOUNTING_DETAILS_FAIL = 'ACCOUNTING_DETAILS_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';
