export const ALL_NOTIFICATIONS_REQUEST = 'ALL_NOTIFICATIONS_REQUEST';
export const ALL_NOTIFICATIONS_SUCCESS = 'ALL_NOTIFICATIONS_SUCCESS';
export const ALL_NOTIFICATIONS_FAIL = 'ALL_NOTIFICATIONS_FAIL';



export const NOTIFICATION_DETAILS_REQUEST = 'NOTIFICATION_DETAILS_REQUEST';
export const NOTIFICATION_DETAILS_SUCCESS = 'NOTIFICATION_DETAILS_SUCCESS';
export const NOTIFICATION_DETAILS_FAIL = 'NOTIFICATION_DETAILS_FAIL';


export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';


export const ADMIN_NOTIFICATIONS_REQUEST = 'ADMIN_NOTIFICATIONS_REQUEST';
export const ADMIN_NOTIFICATIONS_SUCCESS = 'ADMIN_NOTIFICATIONS_SUCCESS';
export const ADMIN_NOTIFICATIONS_FAIL = 'ADMIN_NOTIFICATIONS_FAIL';



export const NEW_NOTIFICATION_REQUEST = 'NEW_NOTIFICATION_REQUEST';
export const NEW_NOTIFICATION_SUCCESS = 'NEW_NOTIFICATION_SUCCESS';
export const NEW_NOTIFICATION_RESET = 'NEW_NOTIFICATION_RESET';
export const NEW_NOTIFICATION_FAIL = 'NEW_NOTIFICATION_FAIL';


export const DELETE_NOTIFICATION_REQUEST = 'DELETE_NOTIFICATION_REQUEST';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_RESET = 'DELETE_NOTIFICATION_RESET';
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_FAIL';


export const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_RESET = 'UPDATE_NOTIFICATION_RESET';
export const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIFICATION_FAIL';


export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_RESET = 'GET_REVIEWS_RESET';
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL';


export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';

//ctrl + d

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
